name: Repository Dispatch
on: 
  repository_dispatch: 
    types: [test]
jobs:
    First-workflow-job:
      name: dispatch job 
      runs-on: ubuntu-latest
      steps:
        - name: command 
          run: ls -la 
          shell: bash
        - name: command 
          run: echo 'hi hi'
          shell: bash
