name: first workflow
on: 
  push: 
    brances: 
        - 'main' 
jobs:
    First-workflow-job:
      name: first job 
      runs-on: ubuntu-latest
      steps:
        - name: before command 
          run: ls -la 
          shell: bash
          
        - name: checkout step 
          uses: actions/checkout@v3

        - name: after command 
          run: ls -la 
          shell: bash