name: Repository Dispatch
on: 
  repository_dispatch: 
    types: [test]
  push:
    branches:
      - 'main'
jobs:
    First-workflow-job:
      name: dispatch job 
      runs-on: ubuntu-latest
      container:
          image: node:14.16
      steps:
        - name: testnodeversion
          run: node -v 
          