name: first workflow
on: 
  push: 
    brances: 
        - 'main' 
jobs:
    First-workflow-job:
      name: first job 
      runs-on: ubuntu-latest
      steps:
        - name: command 
          run: echo  "first job done" 
          shell: bash